### ISSUE TITLE
Getting Error While Running `python3 setup.py develop`

### ISSUE THREAD

**Issue by ErcBunny** [hailanyi/TED#4]
My commands:
```
git clone https://github.com/hailanyi/TED.git
cd TED
pip3 install -r requirements.txt
python3 setup.py develop
```
Then I get errors saying that `THC/THC.h` is missing.
```
python3 setup.py develop
running develop
/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing pcdet.egg-info/PKG-INFO
writing dependency_links to pcdet.egg-info/dependency_links.txt
writing requirements to pcdet.egg-info/requires.txt
writing top-level names to pcdet.egg-info/top_level.txt
reading manifest file 'pcdet.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'pcdet.egg-info/SOURCES.txt'
running build_ext
building 'pcdet.ops.votr_ops.votr_ops_cuda' extension
Emitting ninja build file /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/7] c++ -MMD -MF /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/group_features.o.d -pthread -B /home/yueqian/App/miniconda3/envs/pytorch/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/yueqian/App/miniconda3/envs/pytorch/include -fPIC -O2 -isystem /home/yueqian/App/miniconda3/envs/pytorch/include -fPIC -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/TH -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/THC -I/home/yueqian/App/miniconda3/envs/pytorch/include -I/home/yueqian/App/miniconda3/envs/pytorch/include/python3.9 -c -c /home/yueqian/Dev/machine-perception/assignment/TED/pcdet/ops/votr_ops/src/group_features.cpp -o /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/group_features.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/group_features.o 
c++ -MMD -MF /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/group_features.o.d -pthread -B /home/yueqian/App/miniconda3/envs/pytorch/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/yueqian/App/miniconda3/envs/pytorch/include -fPIC -O2 -isystem /home/yueqian/App/miniconda3/envs/pytorch/include -fPIC -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/TH -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/THC -I/home/yueqian/App/miniconda3/envs/pytorch/include -I/home/yueqian/App/miniconda3/envs/pytorch/include/python3.9 -c -c /home/yueqian/Dev/machine-perception/assignment/TED/pcdet/ops/votr_ops/src/group_features.cpp -o /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/group_features.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
/home/yueqian/Dev/machine-perception/assignment/TED/pcdet/ops/votr_ops/src/group_features.cpp:12:10: fatal error: THC/THC.h: No such file or directory
   12 | #include <THC/THC.h>
      |          ^~~~~~~~~~~
compilation terminated.
[2/7] c++ -MMD -MF /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/build_mapping.o.d -pthread -B /home/yueqian/App/miniconda3/envs/pytorch/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/yueqian/App/miniconda3/envs/pytorch/include -fPIC -O2 -isystem /home/yueqian/App/miniconda3/envs/pytorch/include -fPIC -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/TH -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/THC -I/home/yueqian/App/miniconda3/envs/pytorch/include -I/home/yueqian/App/miniconda3/envs/pytorch/include/python3.9 -c -c /home/yueqian/Dev/machine-perception/assignment/TED/pcdet/ops/votr_ops/src/build_mapping.cpp -o /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/build_mapping.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/build_mapping.o 
c++ -MMD -MF /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/build_mapping.o.d -pthread -B /home/yueqian/App/miniconda3/envs/pytorch/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/yueqian/App/miniconda3/envs/pytorch/include -fPIC -O2 -isystem /home/yueqian/App/miniconda3/envs/pytorch/include -fPIC -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/TH -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/THC -I/home/yueqian/App/miniconda3/envs/pytorch/include -I/home/yueqian/App/miniconda3/envs/pytorch/include/python3.9 -c -c /home/yueqian/Dev/machine-perception/assignment/TED/pcdet/ops/votr_ops/src/build_mapping.cpp -o /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/build_mapping.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
/home/yueqian/Dev/machine-perception/assignment/TED/pcdet/ops/votr_ops/src/build_mapping.cpp:8:10: fatal error: THC/THC.h: No such file or directory
    8 | #include <THC/THC.h>
      |          ^~~~~~~~~~~
compilation terminated.
[3/7] c++ -MMD -MF /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/build_attention_indices.o.d -pthread -B /home/yueqian/App/miniconda3/envs/pytorch/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/yueqian/App/miniconda3/envs/pytorch/include -fPIC -O2 -isystem /home/yueqian/App/miniconda3/envs/pytorch/include -fPIC -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/TH -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/THC -I/home/yueqian/App/miniconda3/envs/pytorch/include -I/home/yueqian/App/miniconda3/envs/pytorch/include/python3.9 -c -c /home/yueqian/Dev/machine-perception/assignment/TED/pcdet/ops/votr_ops/src/build_attention_indices.cpp -o /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/build_attention_indices.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/build_attention_indices.o 
c++ -MMD -MF /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/build_attention_indices.o.d -pthread -B /home/yueqian/App/miniconda3/envs/pytorch/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/yueqian/App/miniconda3/envs/pytorch/include -fPIC -O2 -isystem /home/yueqian/App/miniconda3/envs/pytorch/include -fPIC -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/TH -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/THC -I/home/yueqian/App/miniconda3/envs/pytorch/include -I/home/yueqian/App/miniconda3/envs/pytorch/include/python3.9 -c -c /home/yueqian/Dev/machine-perception/assignment/TED/pcdet/ops/votr_ops/src/build_attention_indices.cpp -o /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/build_attention_indices.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
/home/yueqian/Dev/machine-perception/assignment/TED/pcdet/ops/votr_ops/src/build_attention_indices.cpp:8:10: fatal error: THC/THC.h: No such file or directory
    8 | #include <THC/THC.h>
      |          ^~~~~~~~~~~
compilation terminated.
[4/7] c++ -MMD -MF /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/votr_api.o.d -pthread -B /home/yueqian/App/miniconda3/envs/pytorch/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/yueqian/App/miniconda3/envs/pytorch/include -fPIC -O2 -isystem /home/yueqian/App/miniconda3/envs/pytorch/include -fPIC -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/TH -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/THC -I/home/yueqian/App/miniconda3/envs/pytorch/include -I/home/yueqian/App/miniconda3/envs/pytorch/include/python3.9 -c -c /home/yueqian/Dev/machine-perception/assignment/TED/pcdet/ops/votr_ops/src/votr_api.cpp -o /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/votr_api.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
[5/7] /home/yueqian/App/miniconda3/envs/pytorch/bin/nvcc  -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/TH -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/THC -I/home/yueqian/App/miniconda3/envs/pytorch/include -I/home/yueqian/App/miniconda3/envs/pytorch/include/python3.9 -c -c /home/yueqian/Dev/machine-perception/assignment/TED/pcdet/ops/votr_ops/src/build_mapping_gpu.cu -o /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/build_mapping_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
[6/7] /home/yueqian/App/miniconda3/envs/pytorch/bin/nvcc  -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/TH -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/THC -I/home/yueqian/App/miniconda3/envs/pytorch/include -I/home/yueqian/App/miniconda3/envs/pytorch/include/python3.9 -c -c /home/yueqian/Dev/machine-perception/assignment/TED/pcdet/ops/votr_ops/src/build_attention_indices_gpu.cu -o /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/build_attention_indices_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
[7/7] /home/yueqian/App/miniconda3/envs/pytorch/bin/nvcc  -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/TH -I/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/THC -I/home/yueqian/App/miniconda3/envs/pytorch/include -I/home/yueqian/App/miniconda3/envs/pytorch/include/python3.9 -c -c /home/yueqian/Dev/machine-perception/assignment/TED/pcdet/ops/votr_ops/src/group_features_gpu.cu -o /home/yueqian/Dev/machine-perception/assignment/TED/build/temp.linux-x86_64-cpython-39/pcdet/ops/votr_ops/src/group_features_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yueqian/Dev/machine-perception/assignment/TED/setup.py", line 34, in <module>
    setup(
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
    objects = self.compiler.compile(
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1573, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/yueqian/App/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by ErcBunny** [comment]
I am using PyTorch 1.13. As https://github.com/open-mmlab/mmdetection3d/issues/1332#issuecomment-1085991179 suggests, using an older version of PyTorch solves the issue. Closing the thread. Cheers.

**Comment by IbrahimUWA** [comment]
Hello, I got the same problem using Pytorch 1.8.1, GCC 10.3, Ubuntu 18.04, CUDA 11.1 Python 3.9 and SPCON 2.2.  I also tried with pytorch 1.8.1 and spconv 1.2.1 but I could not get through. Please guide me how to do proper configuration. I will be very thankful to you.

**Comment by ErcBunny** [comment]
> Hello, I got the same problem using Pytorch 1.8.1, GCC 10.3, Ubuntu 18.04, CUDA 11.1 Python 3.9 and SPCON 2.2.  I also tried with pytorch 1.8.1 and spconv 1.2.1 but I could not get through. Please guide me how to do proper configuration. I will be very thankful to you. 

Unfortunately I did not record my setup procedures and I'm not using code in this repo anymore so I cannot offer a helpful guide.

Reproducibility is truly a concern  in academia nowadays. I do really hope that every repo can provide a tested instruction or environment file.

**Comment by ErcBunny** [comment]
![image](https://github.com/hailanyi/TED/assets/41948542/7a1bda99-b0ea-4251-ab44-56db314fe0eb)

An environment file like this absolutely makes the repo less reproducible as versions are not specified. I truly wish to have a conda env file.

**Comment by IbrahimUWA** [comment]
I tried with Python 3.9, SPCON 2.2 and Cuda version 11.1. It works fine. Make sure you have the same hierarchy of the folders mentioned by the author.

Kind regards
Muhammad Ibrahim

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
